#!/bin/sh

PKG_MGR=""
if [ -n "$(command -v brew)" ]; then
	PKG_MGR="brew"
	echo "Nice, you got a Mac. Time to update this script."
	exit 0
else
	PKG_MGR="apt"
	(sudo apt update -y -qq && sudo apt upgrade -y -qq && sudo apt autoclean -y -qq)
fi

# =====
# install go
# =====
echo "🐹 Installing Go..."
sudo $PKG_MGR install -y -qq golang-go gcc

# =====
# install rust here when I'm a real programmer
# =====
echo "🦀 Not installing Rust..."

# =====
# install nodejs, just use n
# =====
echo "😩 Installing nodejs using n..."
curl -L https://bit.ly/n-install | N_PREFIX=~/.local/n bash -s -- -y -n

# =====
# and NOW for bleeding-edge neovim 
# =====
echo "🚀 Getting Neovim prereqs..."
sudo $PKG_MGR install -y -qq clang unzip ripgrep
