#!/usr/bin/env bash

STOW_FOLDERS=("git" "zsh" "nvim" "tmux" "fonts")
DOTFILES=$HOME/dotfiles

pushd ${DOTFILES}
for i in ${!STOW_FOLDERS[@]}; do
    echo "stow ${STOW_FOLDERS[$i]}"
    stow -D ${STOW_FOLDERS[$i]}
    stow ${STOW_FOLDERS[$i]}
done
popd
