#!/bin/sh

echo "👉 If this all works, don't forget to restart your terminal."

PKG_MGR=""
if [ -n "$(command -v brew)" ]; then
	PKG_MGR="brew"
	echo "Nice, you got a Mac. Time to update this script."
	exit 0
else
	PKG_MGR="apt"
	(sudo apt update -y -qq && sudo apt upgrade -y -qq && sudo apt autoclean -y -qq)
fi

# =====
# install some good stuff 
# =====
echo "😎 Installing some good stuff..."
sudo $PKG_MGR install -y -qq make tree stow zsh 

# =====
# stowtime
# =====
zsh $PWD/stowtime

# =====
# install oh-my-zsh
# =====
echo "😱 Installing oh-my-zsh..."
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --keep-zshrc 
